# File system

alias ls='eza -lh --group-directories-first --icons=auto'
alias la='eza -alh --group-directories-first --icons=auto'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'


# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Tools
alias lzg='lazygit'
alias lzd='lazydocker'

# Git
alias gcm='git commit -m'
alias gs="git status"
alias gaa="git add ."
alias gp="git push"

# Commands
alias p='python3'
alias ssha1="eval "$(ssh-agent -s)""
alias ssha2="ssh-add ~/.ssh/gitkey"
alias ssha3="ssh -T git@github.com"

# Gives you what is using the most space. Both directories and files. Varies on current directory
alias most='du -hsx * | sort -rh | head -10'


# Gives you what is using the most space. Both directories and files. Varies on current directory
alias most='du -hsx * | sort -rh | head -10'


# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"


# Shutdown
alias shutdown="sudo shutdown now"
alias restart="sudo reboot now"

# FZF alias and TMUX

alias iv='vim $(fzf --preview "bat --color=always {}")'

alias cfzf='fzf --preview "bat --color=always {}"'

